backend:
  name: git-gateway
  branch: main

local_backend: true

media_library:
  name: uploadcare
  config:
    publicKey: fe63f833548e371aac78
  settings:
    autoFilename: true

media_folder: "public/images/cms"
public_folder: "/images/cms"
collections:
  - label: "Music"
    name: "music"
    folder: "/content/songs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "music" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - {
          label: "Release Date",
          name: "date",
          widget: "datetime",
          format: "MMM D, YYYY",
          date_format: "MM/D/YYYY",
          time_format: false,
          required: false
        }
      - { label: "Genre", name: "genre", widget: "string", required: false }
      - { label: "Artwork", name: "artwork", widget: "image", required: false }
      - {
          label: "Featured on Homepage",
          name: "featured",
          widget: "boolean",
          required: false
        }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Lyrics", name: "lyrics", widget: "markdown", required: false }
      - label: "Stream Links"
        name: "links"
        widget: "object"
        required: false
        fields:
          - { label: "Spotify", name: "spotify", widget: "string", required: false }
          - { label: "Apple Music", name: "apple", widget: "string", required: false }
          - { label: "Youtube", name: "youtube", widget: "string", required: false }
      - {
          label: "Credits",
          name: "credits",
          widget: "list",
          summary: "{{fields.credit}}",
          field:
            {
              label: "Credit",
              name: "credit",
              widget: "select",
              options:
                ["Songwriter", "Producer", "Recording Engineer", "Vocals", "Composer"],
            },
          required: false
        }
      - { 
          label: "Audio File",
          name: "audio",
          widget: "file",
          required: false
        }
  - label: "About"
    name: "about"
    folder: "/content/about"
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
