backend:
  name: git-gateway
  branch: main
media_folder: "public/images/cms"
public_folder: "/images/cms"
collections:
  - name: "music"
    label: "Music"
    folder: "templates/music"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "music" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Release Date", name: "date", widget: "datetime" }
      - { label: "Artwork", name: "artwork", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
